
/*
   Generated file. Do not edit this file manually. Launch `gulp fup:manifest` in order to generate this again.
 */

(function() {
  if (this.ledger == null) {
    this.ledger = {};
  }

  ledger.build = {};

  ledger.build.Mode = 'release';

  ledger.build.Network = 'bitcoin';

  ledger.build.Flavors = ["bitcoin", "release", "all"];

  ledger.build.Time = 1532943969272;

  ledger.build.Commit = '3e6a3a0112b2d78ef4a42619534d348075acc0a4';

  ledger.build.Version = '1.12.1';

}).call(this);
